import { DragEvent, FormEvent, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, BarChart3, CalendarDays, Check, CheckCircle2, Download, Edit3, GripVertical, Menu, Plus, Save, Trash2, X } from "lucide-react";

type EventStatus = "planned" | "completed" | "failed";
type Distance = "near" | "far";
type EventItem = { id: string; title: string; description: string; reason: string; participants: string; organizer: string; steps: string; invite: string; month: number; day: number; status: EventStatus; prerequisite: boolean; distance: Distance };
type FormState = Omit<EventItem, "id" | "month" | "day" | "status" | "prerequisite" | "distance">;
const months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
const initialForm: FormState = { title: "", description: "", reason: "", participants: "", organizer: "", steps: "", invite: "" };
const starterEvents: EventItem[] = [
  { id: "1", title: "Founders breakfast", description: "A focused morning for members to meet and share ideas.", reason: "Build stronger connections early in the year.", participants: "Founders and club members", organizer: "Community team", steps: "Confirm venue; send invitations; prepare talking points", invite: "Maria, James, Aisha", month: 0, day: 8, status: "completed", prerequisite: true, distance: "near" },
  { id: "2", title: "Annual summit", description: "The main strategy and networking event for the club.", reason: "Align members around this year's priorities.", participants: "All active members", organizer: "Executive committee", steps: "Book venue; confirm speakers; publish agenda", invite: "Board and speaker team", month: 2, day: 18, status: "planned", prerequisite: true, distance: "far" },
  { id: "3", title: "Capital circle", description: "A small roundtable about funding and growth.", reason: "Help members learn from practical experience.", participants: "Business owners and investors", organizer: "Partnerships team", steps: "Select guests; prepare questions; send calendar hold", invite: "Investor relations", month: 5, day: 12, status: "planned", prerequisite: false, distance: "far" },
];
const emptyDays = () => Array.from({ length: 30 }, (_, index) => index + 1);

export default function Home() {
  const [month, setMonth] = useState(0);
  const [events, setEvents] = useState<EventItem[]>(starterEvents);
  const [form, setForm] = useState<FormState>(initialForm);
  const [search, setSearch] = useState("");
  const [isSidebarOpen, setIsSidebarOpen] = useState(true);
  const [notice, setNotice] = useState("");
  const [draggedEvent, setDraggedEvent] = useState<EventItem | null>(null);
  const [selectedEvent, setSelectedEvent] = useState<EventItem | null>(null);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [view, setView] = useState<"calendar" | "reports" | "status">("calendar");
  const libraryEvents = useMemo(() => { const query = search.trim().toLowerCase(); return events.filter((event) => !query || `${event.title} ${event.description} ${event.organizer}`.toLowerCase().includes(query)); }, [events, search]);
  const monthEvents = events.filter((event) => event.month === month);
  const planned = events.filter((event) => event.status === "planned").length;
  const completed = events.filter((event) => event.status === "completed").length;
  const failed = events.filter((event) => event.status === "failed").length;
  const prerequisiteMet = events.filter((event) => event.prerequisite).length;
  const near = events.filter((event) => event.distance === "near").length;
  const far = events.filter((event) => event.distance === "far").length;

  function notify(message: string) { setNotice(message); window.setTimeout(() => setNotice(""), 2300); }
  function updateForm(key: keyof FormState, value: string) { setForm((current) => ({ ...current, [key]: value })); }
  function saveEvent(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!form.title.trim()) { notify("Please add an event title first."); return; }
    if (editingId) { setEvents((current) => current.map((item) => item.id === editingId ? { ...item, ...form } : item)); notify("Event updated."); setSelectedEvent((current) => current ? { ...current, ...form } : current); }
    else { setEvents((current) => [...current, { ...form, id: `event-${Date.now()}`, month: -1, day: 0, status: "planned", prerequisite: false, distance: "far" }]); notify("Event saved. Drag its card onto a day."); }
    setForm(initialForm); setEditingId(null);
  }
  function startEdit(item: EventItem) { setForm({ title: item.title, description: item.description, reason: item.reason, participants: item.participants, organizer: item.organizer, steps: item.steps, invite: item.invite }); setEditingId(item.id); setIsSidebarOpen(true); window.scrollTo({ top: 0, behavior: "smooth" }); }
  function startDrag(event: DragEvent<HTMLElement>, item: EventItem) { setDraggedEvent(item); event.dataTransfer.effectAllowed = "move"; event.dataTransfer.setData("text/plain", item.id); }
  function dropOnDay(event: DragEvent<HTMLDivElement>, day: number) { event.preventDefault(); if (!draggedEvent) return; setEvents((current) => current.map((item) => item.id === draggedEvent.id ? { ...item, month, day } : item)); notify(`${draggedEvent.title} placed on ${months[month]} ${day}.`); setDraggedEvent(null); }
  function removeFromCalendar() { if (!selectedEvent) return; const updated = { ...selectedEvent, month: -1, day: 0 }; setEvents((current) => current.map((item) => item.id === selectedEvent.id ? updated : item)); setSelectedEvent(updated); notify("Removed from calendar; kept in saved events."); }
  function deleteEvent() { if (!selectedEvent) return; setEvents((current) => current.filter((item) => item.id !== selectedEvent.id)); notify("Event deleted from saved events."); setSelectedEvent(null); }
  function updateSelected(patch: Partial<EventItem>) { if (!selectedEvent) return; const updated = { ...selectedEvent, ...patch }; setEvents((current) => current.map((item) => item.id === selectedEvent.id ? updated : item)); setSelectedEvent(updated); }
  function updateEventById(id: string, patch: Partial<EventItem>) { setEvents((current) => current.map((item) => item.id === id ? { ...item, ...patch } : item)); setSelectedEvent((current) => current?.id === id ? { ...current, ...patch } : current); }
  function changeMonth(amount: number) { setMonth((current) => (current + amount + 12) % 12); setSelectedEvent(null); }
  function exportReport() {
    const rows = events.map((item) => `<tr><td>${item.title}</td><td>${item.month >= 0 ? `${months[item.month]} ${item.day}` : "Not placed"}</td><td>${item.status}</td><td>${item.prerequisite ? "Met" : "Not met"}</td><td>${item.distance}</td></tr>`).join("");
    const html = `<html><head><meta charset="utf-8"><title>Business Club Planner Report</title><style>body{font-family:Arial;color:#1f2933;padding:30px}h1{color:#2563eb}table{border-collapse:collapse;width:100%}td,th{border:1px solid #dbe1e8;padding:9px;text-align:left}th{background:#e8f0ff}</style></head><body><h1>Business Club Planner Report</h1><p>Annual plan overview for 2026.</p><table><tr><th>Event</th><th>When</th><th>Status</th><th>Prerequisite</th><th>Distance</th></tr>${rows}</table></body></html>`;
    const blob = new Blob([html], { type: "application/msword" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "business-club-planner-report.doc"; link.click(); URL.revokeObjectURL(url); notify("Report downloaded as a Word document.");
  }
  const statCard = (label: string, value: number, total: number, color: string) => <div className="report-stat"><div><span>{label}</span><strong>{value}</strong></div><div className="stat-bar"><i style={{ width: `${total ? Math.round((value / total) * 100) : 0}%`, background: color }} /></div><small>{total ? Math.round((value / total) * 100) : 0}% of events</small></div>;

  return <div className="planner-app">
    <header className="topbar"><div className="brand"><CalendarDays size={21} /><div><strong>Business Club</strong><span>Annual event planner</span></div></div><div className="topbar-title">Annual planner · 2026</div><div className="topbar-actions"><button className="icon-btn mobile-menu" onClick={() => setIsSidebarOpen((value) => !value)} aria-label="Toggle sidebar"><Menu size={19} /></button><button className="save-btn" onClick={() => notify("Planner saved on this device.")}><Save size={15} /> Save</button></div></header>
    <div className="app-body">
      <aside className={`sidebar ${isSidebarOpen ? "open" : "closed"}`}><div className="sidebar-heading"><div><span className="label">{editingId ? "Edit event" : "Create event"}</span><h1>Event details</h1></div><button className="icon-btn collapse-btn" onClick={() => setIsSidebarOpen(false)} aria-label="Close sidebar"><X size={17} /></button></div><p className="helper">{editingId ? "Update the event details and save your changes." : "Fill in the details, save the event, then drag its card into a day."}</p>
        <form className="event-form" onSubmit={saveEvent}>{([ ["title", "Event title", "e.g. Member breakfast", 1], ["description", "Description", "What is this event about?", 3], ["reason", "Reason for event", "Why are we doing it?", 2], ["participants", "Who will participate?", "e.g. Club members", 1], ["organizer", "Who will organize the event?", "e.g. Community team", 1], ["steps", "Which steps should be taken before?", "e.g. Book venue; send invites", 3], ["invite", "Who is called?", "Names or team to contact", 1] ] as const).map(([key, label, placeholder, rows]) => <label key={key}>{label}{rows === 1 ? <input value={form[key]} onChange={(e) => updateForm(key, e.target.value)} placeholder={placeholder} /> : <textarea value={form[key]} onChange={(e) => updateForm(key, e.target.value)} placeholder={placeholder} rows={rows} />}</label>)}<button className="save-event" type="submit">{editingId ? <><Save size={16} /> Update event</> : <><Plus size={16} /> Save event</>}</button>{editingId && <button type="button" className="cancel-edit" onClick={() => { setForm(initialForm); setEditingId(null); }}>Cancel edit</button>}</form>
        <div className="library-header"><div><span className="label">Saved events</span><strong>Drag to a day</strong></div><span className="count">{events.length}</span></div><input className="search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search saved events" /><div className="library-list">{libraryEvents.map((item) => <div key={item.id} className="library-card" draggable onDragStart={(e) => startDrag(e, item)} onClick={() => setSelectedEvent(item)}><div className="library-card-top"><strong>{item.title}</strong><GripVertical size={15} /></div><span>{item.organizer || "Organizer not set"}</span><small>{item.month >= 0 ? `${months[item.month]} ${item.day}` : "Not placed on calendar"}</small><em className={`mini-status ${item.status}`}>{item.status}</em></div>)}{!libraryEvents.length && <div className="empty">No saved events found.</div>}</div>
      </aside>
      <main className="main-content"><div className="view-tabs"><button className={view === "calendar" ? "active" : ""} onClick={() => setView("calendar")}><CalendarDays size={15} /> Calendar</button><button className={view === "status" ? "active" : ""} onClick={() => setView("status")}><CheckCircle2 size={15} /> Status</button><button className={view === "reports" ? "active" : ""} onClick={() => setView("reports")}><BarChart3 size={15} /> Reports</button></div>
        {view === "calendar" && <><div className="page-heading"><div><span className="label">Business club · 2026</span><h2>Plan one month at a time.</h2><p>Save events on the left, then drag them into the 30 day boxes.</p></div><div className="month-switcher"><button className="month-arrow" onClick={() => changeMonth(-1)} aria-label="Previous month"><ArrowLeft size={18} /></button><div><span>Current month</span><strong>{months[month]}</strong></div><button className="month-arrow" onClick={() => changeMonth(1)} aria-label="Next month"><ArrowRight size={18} /></button></div></div><section className="calendar-card"><div className="calendar-header"><div><span className="label">Monthly calendar</span><h3>{months[month]} 2026</h3></div><div className="calendar-note">{monthEvents.length} event{monthEvents.length === 1 ? "" : "s"} placed</div></div><div className="weekday-row">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((day) => <span key={day}>{day}</span>)}</div><div className="day-grid">{emptyDays().map((day) => { const dayEvents = monthEvents.filter((item) => item.day === day); return <div key={day} className={`day-box ${dayEvents.length ? "has-event" : ""}`} onDragOver={(e) => e.preventDefault()} onDrop={(e) => dropOnDay(e, day)}><div className="day-number">{day}</div>{dayEvents.map((item) => <button key={item.id} className={`day-event ${item.status}`} onClick={() => setSelectedEvent(item)} draggable onDragStart={(e) => startDrag(e, item)}><span className="event-dot" /><strong>{item.title}</strong><GripVertical size={12} /></button>)}{!dayEvents.length && <span className="drop-text">Drop here</span>}</div>; })}</div><div className="calendar-footer"><span>Drag a saved event onto any day. Removing it here keeps it in the sidebar.</span><span>30 days · {months[month]}</span></div></section></>}
        {view === "reports" && <Reports events={events} planned={planned} completed={completed} failed={failed} prerequisiteMet={prerequisiteMet} near={near} far={far} exportReport={exportReport} />}
        {view === "status" && <StatusView events={events} updateEventById={updateEventById} setSelectedEvent={setSelectedEvent} startEdit={startEdit} />}
        {view === "calendar" && <section className="details-panel">{selectedEvent ? <><div className="details-title"><div><span className="label">Selected event</span><h3>{selectedEvent.title}</h3></div><div className="details-actions"><button className="edit-btn" onClick={() => startEdit(selectedEvent)}><Edit3 size={15} /> Edit</button><button className="remove-btn" onClick={removeFromCalendar}>Remove from calendar</button><button className="delete-btn" onClick={deleteEvent}><Trash2 size={15} /> Delete</button><button className="icon-btn" onClick={() => setSelectedEvent(null)} aria-label="Close details"><X size={17} /></button></div></div><div className="detail-grid"><div><span>Description</span><p>{selectedEvent.description || "—"}</p></div><div><span>Reason</span><p>{selectedEvent.reason || "—"}</p></div><div><span>Participants</span><p>{selectedEvent.participants || "—"}</p></div><div><span>Organizer</span><p>{selectedEvent.organizer || "—"}</p></div><div><span>Steps before the event</span><p>{selectedEvent.steps || "—"}</p></div><div><span>Who is called</span><p>{selectedEvent.invite || "—"}</p></div></div><div className="inline-status"><strong>Status controls</strong><StatusControls event={selectedEvent} updateSelected={updateSelected} /></div></> : <div className="details-empty"><Check size={18} /><div><strong>Event details</strong><p>Click an event to edit it, remove it from the calendar, or update its status.</p></div></div>}</section>}
      </main>
    </div>{notice && <div className="toast"><Check size={15} /> {notice}</div>}
  </div>;
}

function StatusControls({ event, updateSelected }: { event: EventItem; updateSelected: (patch: Partial<EventItem>) => void }) { return <div className="status-controls"><button className={event.status === "planned" ? "selected planned" : "planned"} onClick={() => updateSelected({ status: "planned" })}>Planned</button><button className={event.status === "completed" ? "selected completed" : "completed"} onClick={() => updateSelected({ status: "completed" })}>Completed</button><button className={event.status === "failed" ? "selected failed" : "failed"} onClick={() => updateSelected({ status: "failed" })}>Failed</button><button className={event.prerequisite ? "selected prerequisite" : "prerequisite"} onClick={() => updateSelected({ prerequisite: !event.prerequisite })}>Prerequisite met</button><button className={event.distance === "near" ? "selected distance" : "distance"} onClick={() => updateSelected({ distance: "near" })}>Near</button><button className={event.distance === "far" ? "selected distance" : "distance"} onClick={() => updateSelected({ distance: "far" })}>Far</button></div>; }
function StatusView({ events, updateEventById, setSelectedEvent, startEdit }: { events: EventItem[]; updateEventById: (id: string, patch: Partial<EventItem>) => void; setSelectedEvent: (event: EventItem) => void; startEdit: (event: EventItem) => void }) { return <div className="status-view"><div className="page-heading"><div><span className="label">Event status</span><h2>Keep every plan moving.</h2><p>Status buttons appear automatically when an event is created.</p></div></div><div className="status-list">{events.map((event) => <article className="status-row" key={event.id}><div><strong>{event.title}</strong><span>{event.month >= 0 ? `${months[event.month]} ${event.day}` : "Not placed"} · {event.organizer || "No organizer"}</span></div><StatusControls event={event} updateSelected={(patch) => { updateEventById(event.id, patch); setSelectedEvent({ ...event, ...patch }); }} /><button className="edit-btn" onClick={() => startEdit(event)}><Edit3 size={14} /> Edit</button></article>)}</div></div>; }
function Reports({ events, planned, completed, failed, prerequisiteMet, near, far, exportReport }: { events: EventItem[]; planned: number; completed: number; failed: number; prerequisiteMet: number; near: number; far: number; exportReport: () => void }) { const total = events.length; return <div className="reports-view"><div className="report-heading"><div><span className="label">Reports</span><h2>Plan overview</h2><p>See what is planned, completed, blocked, near, and far away.</p></div><button className="save-btn" onClick={exportReport}><Download size={15} /> Export .doc</button></div><div className="report-grid">{[ ["Completed", completed, total, "#16a34a"], ["Coming up", planned, total, "#2563eb"], ["Failed", failed, total, "#dc2626"], ["Prerequisite met", prerequisiteMet, total, "#7c3aed"], ["Near", near, total, "#ea580c"], ["Far away", far, total, "#64748b"] ].map(([label, value, all, color]) => <div key={String(label)}>{statCard(String(label), Number(value), Number(all), String(color))}</div>)}</div><div className="report-table-card"><h3>What is planned and when</h3><table><thead><tr><th>Event</th><th>When</th><th>Status</th><th>Prerequisite</th><th>Distance</th></tr></thead><tbody>{events.map((event) => <tr key={event.id}><td>{event.title}</td><td>{event.month >= 0 ? `${months[event.month]} ${event.day}` : "Not placed"}</td><td><span className={`table-status ${event.status}`}>{event.status}</span></td><td>{event.prerequisite ? "Met" : "Not met"}</td><td>{event.distance}</td></tr>)}</tbody></table></div></div>; }
function statCard(label: string, value: number, total: number, color: string) { return <div className="report-stat"><div><span>{label}</span><strong>{value}</strong></div><div className="stat-bar"><i style={{ width: `${total ? Math.round((value / total) * 100) : 0}%`, background: color }} /></div><small>{total ? Math.round((value / total) * 100) : 0}% of events</small></div>; }
